[package]
name = "mnist-trainer"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
model = { path = "../model" }
ndarray = "0.16.1"
